# Generated by Django 5.1.2 on 2024-12-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_product_description_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id']},
        ),
    ]
